export const languageNames: Record<string, string> = {
  text: "텍스트", plaintext: "텍스트", txt: "텍스트", plain: "텍스트",
  powershell: "PowerShell", ps: "PowerShell", ps1: "PowerShell", psm1: "PowerShell", psd1: "PowerShell", pwsh: "PowerShell",
  javascript: "JavaScript", js: "JavaScript", jsx: "JSX",
  typescript: "TypeScript", ts: "TypeScript", tsx: "TSX",
  sql: "SQL", json: "JSON", jsonc: "JSONC", json5: "JSON5",
  html: "HTML", xml: "XML", svg: "SVG", css: "CSS", scss: "SCSS",
  bash: "Bash", sh: "Shell", shell: "Shell", shellscript: "Shell",
  console: "터미널", shellsession: "터미널", "shell-session": "터미널", zsh: "Zsh", fish: "Fish",
  python: "Python", py: "Python", http: "HTTP", https: "HTTP",
  yaml: "YAML", yml: "YAML", toml: "TOML", ini: "INI", dotenv: "환경 변수", env: "환경 변수",
  markdown: "Markdown", md: "Markdown", diff: "Diff", patch: "Diff",
  c: "C", cpp: "C++", csharp: "C#", cs: "C#", java: "Java",
  go: "Go", rust: "Rust", rs: "Rust", ruby: "Ruby", rb: "Ruby",
  php: "PHP", blade: "Blade", perl: "Perl", raku: "Raku",
  dockerfile: "Dockerfile", docker: "Dockerfile", nginx: "Nginx",
  mjs: "JavaScript", cjs: "JavaScript", mts: "TypeScript", cts: "TypeScript",
  vue: "Vue", svelte: "Svelte", astro: "Astro", angular: "Angular",
  sass: "Sass", less: "Less", stylus: "Stylus", postcss: "PostCSS",
  graphql: "GraphQL", gql: "GraphQL", mdx: "MDX", latex: "LaTeX", tex: "LaTeX",
  kt: "Kotlin", kotlin: "Kotlin", scala: "Scala", swift: "Swift", dart: "Dart",
  r: "R", julia: "Julia", lua: "Lua", luau: "Luau", zig: "Zig",
  cxx: "C++", cc: "C++", "c++": "C++", h: "C", hpp: "C++",
  "c#": "C#", "objective-c": "Objective-C", objc: "Objective-C",
  "objective-cpp": "Objective-C++", fsharp: "F#", fs: "F#", "f#": "F#",
  elixir: "Elixir", ex: "Elixir", erlang: "Erlang", clojure: "Clojure",
  haskell: "Haskell", hs: "Haskell", ocaml: "OCaml", scheme: "Scheme",
  lisp: "Lisp", commonlisp: "Common Lisp", racket: "Racket",
  "emacs-lisp": "Emacs Lisp", elisp: "Emacs Lisp",
  bat: "Batch", batch: "Batch", cmd: "Batch", awk: "AWK",
  makefile: "Makefile", make: "Makefile", cmake: "CMake",
  terraform: "Terraform", hcl: "HCL", tf: "Terraform", nix: "Nix",
  prisma: "Prisma", protobuf: "Protocol Buffers", proto: "Protocol Buffers",
  csv: "CSV", tsv: "TSV", jsonl: "JSON Lines", ndjson: "JSON Lines",
  httprequest: "HTTP", tcp: "TCP", log: "로그", properties: "Properties",
  mysql: "MySQL", mariadb: "MariaDB", postgresql: "PostgreSQL", postgres: "PostgreSQL", pgsql: "PostgreSQL",
  sqlite: "SQLite", oracle: "Oracle SQL", plsql: "PL/SQL", tsql: "T-SQL", sqlserver: "T-SQL",
  mssql: "T-SQL", transactsql: "T-SQL", db2: "DB2 SQL", db2i: "DB2 for i SQL",
  bigquery: "BigQuery SQL", snowflake: "Snowflake SQL", redshift: "Redshift SQL",
  duckdb: "DuckDB SQL", clickhouse: "ClickHouse SQL", hive: "Hive SQL", spark: "Spark SQL",
  trino: "Trino SQL", presto: "Presto SQL", tidb: "TiDB SQL", singlestoredb: "SingleStore SQL", n1ql: "N1QL",
  lwc: "LWC", mjml: "MJML", flow: "Flow", kotlin_script: "Kotlin", objcpp: "Objective-C++", "objective-c++": "Objective-C++",
  handlebars: "Handlebars", hbs: "Handlebars", liquid: "Liquid", pug: "Pug",
  regex: "정규 표현식", regexp: "정규 표현식", wasm: "WebAssembly", wat: "WebAssembly",
  asm: "Assembly", assembly: "Assembly", nasm: "Assembly", mermaid: "Mermaid",
}
