import { test, expect } from '@playwright/test'

const messages: string[] = []
test.beforeEach(async ({ page }) => {
  messages.length = 0
  page.on('pageerror', error => messages.push(error.message))
  page.on('console', message => { if (message.type() === 'error') messages.push(message.text()) })
  await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort())
})
test.afterEach(() => expect(messages).toEqual([]))

const searchName = '제목, 본문, 번호 검색'
test('number search, difficulty intersection and reset keep usable controls', async ({ page }) => {
  await page.goto('./?view=all&topic=sql-injection')
  const input = page.getByRole('searchbox', { name: searchName })
  await expect(page.locator('.lab-group')).toHaveCount(1)
  await input.fill('#０１．０２')
  await expect(page.locator('.note-row')).toHaveCount(1)
  await expect(page.locator('.note-title')).toContainText('로그인')
  await expect(input).toBeFocused()
  await page.getByRole('combobox', { name: '난이도', exact: true }).selectOption('Expert')
  await expect(page.locator('.note-row')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '검색 결과가 없습니다.' })).toBeVisible()
  await page.locator('.results-heading').getByRole('button', { name: '필터 초기화' }).click()
  await expect(page.locator('.note-row')).toHaveCount(24)
  await expect(input).toHaveValue('')
  await expect(input).toBeFocused()
  expect(new URL(page.url()).search).toBe('')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('legacy query filters and group sort survive direct visits and browser back', async ({ page }) => {
  await page.goto('./?view=all&topic=sql-injection&level=Practitioner&sort=difficulty')
  await expect(page.getByRole('combobox', { name: '주제', exact: true })).toHaveValue('sql-injection')
  await expect(page.getByRole('combobox', { name: '난이도', exact: true })).toHaveValue('Practitioner')
  await expect(page.getByRole('combobox', { name: '주제 안 정렬' })).toHaveValue('difficulty')
  const levels = await page.locator('.note-row .note-level').allTextContents()
  expect(levels.length).toBeGreaterThan(0)
  expect(levels.every(level => level === '실전')).toBe(true)
  await page.getByRole('combobox', { name: '주제 안 정렬' }).selectOption('recent')
  await expect.poll(() => new URL(page.url()).searchParams.get('sort')).toBe('recent')
  const dates = await page.locator('.note-updated time').evaluateAll(elements => elements.map(element => Date.parse(element.getAttribute('datetime')!)))
  expect(dates.length).toBeGreaterThan(0)
  expect(dates.every((date, i) => i === 0 || dates[i - 1] >= date)).toBe(true)
  await page.goBack()
  await expect(page.getByRole('combobox', { name: '주제 안 정렬' })).toHaveValue('difficulty')
  await expect(page.locator('.note-updated')).toHaveCount(0)
})

test('load more has a shareable reload-safe length and focuses the new rows', async ({ page }) => {
  await page.goto('./')
  await expect(page.locator('.note-row')).toHaveCount(24)
  await page.getByRole('button', { name: /^더 보기/ }).click()
  await expect(page.locator('.note-row')).toHaveCount(48)
  await expect(page.locator('.note-title a').nth(24)).toBeFocused()
  expect(new URL(page.url()).searchParams.get('limit')).toBe('48')
  await page.reload()
  await expect(page.locator('.note-row')).toHaveCount(48)
  await page.getByRole('combobox', { name: '주제', exact: true }).selectOption('sql-injection')
  await expect(page.locator('.lab-group')).toHaveCount(1)
  expect(new URL(page.url()).searchParams.has('limit')).toBe(false)
  await page.goBack()
  await expect(page.locator('.note-row')).toHaveCount(48)
})

test('Korean IME composition commits only when complete and preserves input focus', async ({ page }) => {
  await page.goto('./')
  const input = page.getByRole('searchbox', { name: searchName })
  await input.focus()
  await input.dispatchEvent('compositionstart')
  await input.fill('오라클')
  await page.waitForTimeout(220)
  expect(new URL(page.url()).searchParams.has('q')).toBe(false)
  await expect(input).toHaveValue('오라클')
  await input.dispatchEvent('compositionend', { data: '오라클' })
  await expect.poll(() => new URL(page.url()).searchParams.get('q')).toBe('오라클')
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('오라클')
  expect(await page.locator('.note-row').count()).toBeGreaterThan(0)
  await input.press('Escape')
  await expect(input).toHaveValue('')
  await expect(page.locator('.note-row')).toHaveCount(24)
  await input.pressSequentially('oracle', { delay: 145 })
  await expect.poll(() => new URL(page.url()).searchParams.get('q')).toBe('oracle')
  await expect(input).toHaveValue('oracle')
  await expect(input).toBeFocused()
})
