import { expect, test } from '@playwright/test'
import { basePath } from '../site.config.mjs'

const first = 'labs/sql-injection/lab-retrieve-hidden-data.html'
const second = 'labs/sql-injection/lab-login-bypass.html'
const errors: string[] = []

test.beforeEach(async ({ page }) => {
  errors.length = 0
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort())
})
test.afterEach(() => expect(errors).toEqual([]))

test('header search supports keyboard, composition and route synchronization', async ({ page }) => {
  await page.goto(first)
  await expect(page.locator('article')).toBeVisible()
  await page.keyboard.press('Control+k')
  const search = page.getByRole('searchbox', { name: '전체 노트 검색어' })
  await expect(search).toBeFocused()
  await search.fill('로그인')
  await search.dispatchEvent('compositionstart')
  await page.locator('.header-search').dispatchEvent('submit')
  await expect(page).toHaveURL(new RegExp(first.replace('.', '\\.') + '$'))
  await search.dispatchEvent('compositionend')
  await search.press('Enter')
  await expect(page).toHaveURL(new RegExp(`${basePath}\\?q=`))
  await expect(page.locator('.library-title')).toHaveText('포트스위거 풀이 노트')
  await expect(search).toHaveValue('로그인')
  await search.fill('미완성 입력')
  await search.press('Escape')
  await expect(search).toHaveValue('로그인')
  await expect(search).not.toBeFocused()
  await page.goBack()
  await expect(page.locator('article')).toBeVisible()
  await expect(search).toHaveValue('')
  await page.goForward()
  await expect(search).toHaveValue('로그인')
})

test('history entry restores list length and document position without visibility jumps', async ({ page }) => {
  await page.goto('./?limit=48')
  const rows = page.locator('.note-row')
  await expect(rows).toHaveCount(48)
  const note = rows.nth(39).locator('.note-title a')
  await note.scrollIntoViewIfNeeded()
  const y = await page.evaluate(() => window.scrollY)
  expect(y).toBeGreaterThan(500)
  await note.click()
  await expect(page.locator('article')).toBeVisible()
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(0)
  await page.goBack()
  await expect(rows).toHaveCount(48)
  await expect.poll(() => page.evaluate(() => scrollY)).toBeCloseTo(y, -1)
  await page.reload()
  await expect(rows).toHaveCount(48)
  await expect(page.locator('html')).not.toHaveAttribute('data-initial-scroll', 'pending')
  await expect.poll(() => page.evaluate(() => scrollY)).toBeCloseTo(y, -1)
  expect(await page.locator('html').evaluate(element => element.style.getPropertyValue('--initial-scroll-height'))).toBe('')
  await page.evaluate(() => window.scrollTo(0, 480))
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(480)
  await page.evaluate(() => {
    document.dispatchEvent(new Event('visibilitychange'))
    window.dispatchEvent(new Event('pageshow'))
    window.dispatchEvent(new Event('resize'))
  })
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  expect(await page.evaluate(() => scrollY)).toBe(480)
  await page.goForward()
  await expect(page.locator('article')).toBeVisible()
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(0)
})

test('late initial fonts do not take the page away from user scrolling', async ({ page }) => {
  let release: () => void = () => {}
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/*.woff2', async route => { await gate; await route.continue().catch(() => {}) })
  try {
    await page.goto('./?limit=48', { waitUntil: 'domcontentloaded' })
    await expect(page.locator('.note-row')).toHaveCount(48)
    await expect(page.locator('html')).toHaveAttribute('data-initial-scroll', 'pending')
    await page.evaluate(() => window.scrollTo(0, 800))
    await expect.poll(() => page.evaluate(() => scrollY)).toBe(800)
    release()
    await expect(page.locator('html')).not.toHaveAttribute('data-initial-scroll', 'pending')
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
    expect(await page.evaluate(() => scrollY)).toBe(800)
    if (await page.evaluate(() => CSS.supports('overflow-anchor', 'auto'))) expect(await page.locator('html').evaluate(element => getComputedStyle(element).overflowAnchor)).toBe('auto')
  } finally { release() }
})

test('desktop Explorer keeps folders and independent collection scroll after navigation and reload', async ({ page, isMobile }) => {
  test.skip(isMobile, 'Desktop persistent Explorer is checked at desktop viewport.')
  await page.goto('./')
  const tree = page.locator('.topic-tree')
  await expect(page.locator('.topic-children a')).toHaveCount(0)
  await page.locator('.topic-expand').nth(0).click()
  await page.locator('.topic-expand').nth(1).click()
  await expect(page.locator('.topic-children:not([hidden])')).toHaveCount(2)
  await tree.evaluate(element => { element.scrollTop = 650 })
  await expect.poll(() => tree.evaluate(element => element.scrollTop)).toBe(650)
  await page.locator('.explorer-shortcuts a').filter({ hasText: '개념 노트' }).click()
  await expect(page.locator('.topic-browser')).toHaveAttribute('data-explorer-mode', 'concepts')
  await expect(page.locator('.topic-empty')).toContainText('개념 노트')
  await page.locator('.explorer-shortcuts a').filter({ hasText: '풀이 노트' }).click()
  await expect(page.locator('.topic-children:not([hidden])')).toHaveCount(2)
  await expect.poll(() => tree.evaluate(element => element.scrollTop)).toBe(650)
  await page.locator(`.note-title a[href="${basePath + first}"]`).click()
  await expect(page.locator('article')).toBeVisible()
  await expect.poll(() => tree.evaluate(element => element.scrollTop)).toBe(650)
  await page.reload()
  await expect(page.locator('.topic-children:not([hidden])')).toHaveCount(2)
  await expect.poll(() => tree.evaluate(element => element.scrollTop)).toBe(650)
})

test('mobile Explorer waits for committed navigation and releases focus at breakpoints', async ({ page, isMobile }) => {
  test.skip(!isMobile, 'Inline mobile Explorer is checked in touch emulation.')
  // A saved desktop preference must not prevent the mobile panel from opening.
  await page.addInitScript(() => localStorage.setItem('faultline:explorer:collapsed', 'true'))
  await page.goto('./?topic=sql-injection')
  expect(await page.locator('.notebook-nav').evaluate(element => getComputedStyle(element).display)).toBe('grid')
  expect(await page.locator('#header-search').evaluate(element => getComputedStyle(element).fontSize)).toBe('16px')
  const toggle = page.locator('.topic-mobile-toggle')
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await page.keyboard.press('Escape')
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(toggle).toBeFocused()
  await toggle.click()
  let release: () => void = () => {}
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/*.data*', async route => { await gate; await route.continue().catch(() => {}) })
  await page.locator(`.topic-children a[href="${basePath + first}"]`).click()
  await expect(page.locator('.notebook-nav')).toHaveAttribute('data-pending', 'true')
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await page.locator(`.topic-children a[href="${basePath + second}"]`).click()
  release()
  await expect(page).toHaveURL(new RegExp(second.replace('.', '\\.') + '$'))
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(page.locator('#main-content')).toBeFocused()
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(0)
  await toggle.click()
  await page.setViewportSize({ width: 1100, height: 850 })
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await page.setViewportSize({ width: 412, height: 850 })
  await expect(toggle).toBeVisible()
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  expect(await page.evaluate(() => document.body.style.overflow)).toBe('')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Explorer renders all difficulty levels on a direct article load', async ({ page, isMobile }) => {
  await page.goto('labs/authentication/password-based-lab-username-enumeration-via-different-responses.html')
  if (isMobile) await page.locator('.topic-mobile-toggle').click()
  const tree = page.locator('.topic-tree')
  await expect(page.locator('.explorer-shortcuts a').first()).toContainText('포트스위거 풀이 노트')
  for (const [label, count] of [['입문 · Apprentice', 1], ['실전 · Practitioner', 2], ['심화 · Expert', 3]] as const) {
    const rating = tree.getByRole('img', { name: `난이도 ${label}`, exact: true }).first()
    await rating.scrollIntoViewIfNeeded()
    await expect(rating).toBeVisible()
    await expect(rating.locator('.is-filled')).toHaveCount(count)
    await expect(rating.locator('.is-empty')).toHaveCount(3 - count)
    if (count < 3) await expect(rating.locator('.is-empty').first()).toHaveCSS('fill', 'none')
  }
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Explorer icon accents are neutral until hovered, opened or selected', async ({ page, isMobile }) => {
  await page.goto('./')
  if (isMobile) await page.locator('.topic-mobile-toggle').click()
  const entry = page.locator('.topic-entry').first()
  const accent = entry.locator('.topic-icon-accent').first()
  const color = () => accent.evaluate(element => getComputedStyle(element).stroke)
  const neutral = await color()
  expect(neutral).toBe(await entry.locator('.topic-icon').evaluate(element => getComputedStyle(element).color))
  await entry.locator('.topic-expand').click()
  expect(await color()).not.toBe(neutral)
  await entry.locator('.topic-expand').click()
  await page.mouse.move(0, 0)
  expect(await color()).toBe(neutral)
  await entry.locator('.topic-name').click()
  if (isMobile) await page.locator('.topic-mobile-toggle').click()
  expect(await color()).not.toBe(neutral)
  const other = page.locator('.topic-entry').nth(1)
  expect(await other.locator('.topic-icon-accent').first().evaluate(element => getComputedStyle(element).stroke)).toBe(neutral)
})

test('desktop Explorer collapse preserves navigation, scroll and the first paint on reload', async ({ page, isMobile }) => {
  test.skip(isMobile, 'Desktop collapse is independent from the mobile panel.')
  await page.goto('./?topic=sql-injection')
  const tree = page.locator('.topic-tree')
  const panel = page.locator('#topic-note-panel')
  const toggle = page.locator('.explorer-desktop-toggle')
  await expect(page.locator('.topic-children:not([hidden])')).toHaveCount(1)
  await tree.evaluate(element => { element.scrollTop = 650 })
  await expect.poll(() => tree.evaluate(element => element.scrollTop)).toBe(650)
  const expandedWidth = await page.locator('.site-content').evaluate(element => element.getBoundingClientRect().width)
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(toggle).toHaveAccessibleName('탐색기 열기')
  await expect(toggle).toBeFocused()
  await expect(panel).toBeHidden()
  expect(await page.locator('.site-content').evaluate(element => element.getBoundingClientRect().width)).toBeGreaterThan(expandedWidth)
  await page.locator(`.note-title a[href="${basePath + first}"]`).click()
  await expect(page.locator('article')).toBeVisible()
  await expect(panel).toBeHidden()

  let release: () => void = () => {}
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/*.js', async route => { await gate; await route.continue().catch(() => {}) })
  try {
    await page.reload({ waitUntil: 'commit' })
    // Saved layout is applied before the React bundle can run.
    await expect(page.locator('.sidebar')).toHaveCSS('width', '56px')
    await expect(panel).toBeHidden()
  } finally { release() }
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await toggle.click()
  await expect(panel).toBeVisible()
  await expect.poll(() => tree.evaluate(element => element.scrollTop)).toBe(650)
  await page.goBack()
  await expect(page.locator('.library-title')).toHaveText('포트스위거 풀이 노트')
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await expect.poll(() => tree.evaluate(element => element.scrollTop)).toBe(650)

  await toggle.click()
  await page.setViewportSize({ width: 700, height: 850 })
  const mobileToggle = page.locator('.topic-mobile-toggle')
  await expect(mobileToggle).toBeFocused()
  await mobileToggle.click()
  await expect(panel).toBeVisible()
  await page.setViewportSize({ width: 1440, height: 900 })
  await expect(panel).toBeHidden()
  await expect(toggle).toBeFocused()
  await toggle.click()
  await expect(panel).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
