import { expect, test } from '@playwright/test'
import { basePath } from '../site.config.mjs'

const first = 'labs/sql-injection/lab-retrieve-hidden-data.html'
const second = 'labs/sql-injection/lab-login-bypass.html'
const errors: string[] = []

test.beforeEach(async ({ page }) => {
  errors.length = 0
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort())
})
test.afterEach(() => expect(errors).toEqual([]))

test('header search supports keyboard, composition and route synchronization', async ({ page }) => {
  await page.goto(first)
  await expect(page.locator('article')).toBeVisible()
  await page.keyboard.press('Control+k')
  const search = page.getByRole('searchbox', { name: '전체 노트 검색어' })
  await expect(search).toBeFocused()
  await search.fill('로그인')
  await search.dispatchEvent('compositionstart')
  await page.locator('.header-search').dispatchEvent('submit')
  await expect(page).toHaveURL(new RegExp(first.replace('.', '\\.') + '$'))
  await search.dispatchEvent('compositionend')
  await search.press('Enter')
  await expect(page).toHaveURL(new RegExp(`${basePath}\\?q=`))
  await expect(page.locator('.library-title')).toHaveText('풀이 노트')
  await expect(search).toHaveValue('로그인')
  await search.fill('미완성 입력')
  await search.press('Escape')
  await expect(search).toHaveValue('로그인')
  await expect(search).not.toBeFocused()
  await page.goBack()
  await expect(page.locator('article')).toBeVisible()
  await expect(search).toHaveValue('')
  await page.goForward()
  await expect(search).toHaveValue('로그인')
})

test('history entry restores list length and document position without visibility jumps', async ({ page }) => {
  await page.goto('./?limit=48')
  const rows = page.locator('.note-row')
  await expect(rows).toHaveCount(48)
  const note = rows.nth(39).locator('.note-title a')
  await note.scrollIntoViewIfNeeded()
  const y = await page.evaluate(() => window.scrollY)
  expect(y).toBeGreaterThan(500)
  await note.click()
  await expect(page.locator('article')).toBeVisible()
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(0)
  await page.goBack()
  await expect(rows).toHaveCount(48)
  await expect.poll(() => page.evaluate(() => scrollY)).toBeCloseTo(y, -1)
  await page.reload()
  await expect(rows).toHaveCount(48)
  await expect(page.locator('html')).not.toHaveAttribute('data-initial-scroll', 'pending')
  await expect.poll(() => page.evaluate(() => scrollY)).toBeCloseTo(y, -1)
  await page.evaluate(() => window.scrollTo(0, 480))
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(480)
  await page.evaluate(() => {
    document.dispatchEvent(new Event('visibilitychange'))
    window.dispatchEvent(new Event('pageshow'))
    window.dispatchEvent(new Event('resize'))
  })
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  expect(await page.evaluate(() => scrollY)).toBe(480)
  await page.goForward()
  await expect(page.locator('article')).toBeVisible()
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(0)
})

test('late initial fonts do not take the page away from user scrolling', async ({ page }) => {
  let release: () => void = () => {}
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/*.woff2', async route => { await gate; await route.continue().catch(() => {}) })
  try {
    await page.goto('./?limit=48', { waitUntil: 'domcontentloaded' })
    await expect(page.locator('.note-row')).toHaveCount(48)
    await expect(page.locator('html')).toHaveAttribute('data-initial-scroll', 'pending')
    await page.evaluate(() => window.scrollTo(0, 800))
    await expect.poll(() => page.evaluate(() => scrollY)).toBe(800)
    release()
    await expect(page.locator('html')).not.toHaveAttribute('data-initial-scroll', 'pending')
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
    expect(await page.evaluate(() => scrollY)).toBe(800)
    if (await page.evaluate(() => CSS.supports('overflow-anchor', 'auto'))) expect(await page.locator('html').evaluate(element => getComputedStyle(element).overflowAnchor)).toBe('auto')
  } finally { release() }
})

test('desktop Explorer keeps folders and independent collection scroll after navigation and reload', async ({ page, isMobile }) => {
  test.skip(isMobile, 'Desktop persistent Explorer is checked at desktop viewport.')
  await page.goto('./')
  const tree = page.locator('.topic-tree')
  await expect(page.locator('.topic-children a')).toHaveCount(0)
  await page.locator('.topic-expand').nth(0).click()
  await page.locator('.topic-expand').nth(1).click()
  await expect(page.locator('.topic-children:not([hidden])')).toHaveCount(2)
  await tree.evaluate(element => { element.scrollTop = 650 })
  await expect.poll(() => tree.evaluate(element => element.scrollTop)).toBe(650)
  await page.locator('.explorer-shortcuts a').filter({ hasText: '개념 노트' }).click()
  await expect(page.locator('.topic-browser')).toHaveAttribute('data-explorer-mode', 'concepts')
  await expect(page.locator('.topic-empty')).toContainText('개념 노트')
  await page.locator('.explorer-shortcuts a').filter({ hasText: '풀이 노트' }).click()
  await expect(page.locator('.topic-children:not([hidden])')).toHaveCount(2)
  await expect.poll(() => tree.evaluate(element => element.scrollTop)).toBe(650)
  await page.locator(`.note-title a[href="${basePath + first}"]`).click()
  await expect(page.locator('article')).toBeVisible()
  await expect.poll(() => tree.evaluate(element => element.scrollTop)).toBe(650)
  await page.reload()
  await expect(page.locator('.topic-children:not([hidden])')).toHaveCount(2)
  await expect.poll(() => tree.evaluate(element => element.scrollTop)).toBe(650)
})

test('mobile Explorer waits for committed navigation and releases focus at breakpoints', async ({ page, isMobile }) => {
  test.skip(!isMobile, 'Inline mobile Explorer is checked in touch emulation.')
  await page.goto('./?topic=sql-injection')
  expect(await page.locator('.notebook-nav').evaluate(element => getComputedStyle(element).display)).toBe('grid')
  expect(await page.locator('#header-search').evaluate(element => getComputedStyle(element).fontSize)).toBe('16px')
  const toggle = page.locator('.topic-mobile-toggle')
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await page.keyboard.press('Escape')
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(toggle).toBeFocused()
  await toggle.click()
  let release: () => void = () => {}
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/*.data*', async route => { await gate; await route.continue().catch(() => {}) })
  await page.locator(`.topic-children a[href="${basePath + first}"]`).click()
  await expect(page.locator('.notebook-nav')).toHaveAttribute('data-pending', 'true')
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await page.locator(`.topic-children a[href="${basePath + second}"]`).click()
  release()
  await expect(page).toHaveURL(new RegExp(second.replace('.', '\\.') + '$'))
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(page.locator('#main-content')).toBeFocused()
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(0)
  await toggle.click()
  await page.setViewportSize({ width: 1100, height: 850 })
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await page.setViewportSize({ width: 412, height: 850 })
  await expect(toggle).toBeVisible()
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  expect(await page.evaluate(() => document.body.style.overflow)).toBe('')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
