#!/usr/bin/env python3
"""Rebuild the README's self-contained SVG banner (fonttools + brotli)."""

import html
import json
import re
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
font = TTFont(ROOT / "site/assets/fonts/pretendard/PretendardVariable.woff2")
units = font["head"].unitsPerEm
cmap = font.getBestCmap()
glyph_sets = {}
catalog = json.loads((ROOT / "data/labs.json").read_text())
topics, labs = len(catalog["categories"]), len(catalog["labs"])


def number(value):
    return f"{value:.2f}".rstrip("0").rstrip(".") if value else "0"


def label(text, x, y, size, weight=450, color="ink", tracking=0, center=False):
    """Outline lettering so GitHub needs no embedded or external fonts."""
    glyphs = glyph_sets.setdefault(weight, font.getGlyphSet(location={"wght": weight}))
    scale = size / units
    pen = SVGPathPen(glyphs, ntos=number)
    cursor = 0
    for char in text:
        glyph = glyphs[cmap[ord(char)]]
        glyph.draw(TransformPen(pen, (1, 0, 0, 1, cursor, 0)))
        cursor += glyph.width + tracking / scale
    if center:
        x -= (cursor * scale - tracking) / 2
    return (
        f'<g class="{color}" data-label="{html.escape(text, quote=True)}" '
        f'transform="translate({number(x)} {number(y)}) scale({scale} {-scale})">'
        f'<path d="{pen.getCommands()}"/></g>'
    )


def svg_body(relative):
    source = (ROOT / relative).read_text()
    body = re.search(r"<svg\b[^>]*>(.*?)</svg>", source, re.S).group(1)
    return re.sub(r"<style\b[^>]*>.*?</style>|<title>.*?</title>|<!--.*?-->", "", body, flags=re.S).strip()


def topic_icon(name, x, y):
    body = svg_body(f"site/assets/icons/topics/{name}.svg")
    return (
        f'<g transform="translate({x} {y}) scale(1.4)" fill="none" '
        f'stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">{body}</g>'
    )


brand = svg_body("site/assets/favicon/favicon.svg").replace('id="split"', 'id="hero-split"').replace("url(#split)", "url(#hero-split)")
parts = [
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 620" width="1600" height="620" role="img" aria-labelledby="hero-title hero-description">',
    '<title id="hero-title">PortSwigger Lab Notes</title>',
    f'<desc id="hero-description">{topics}개 주제, {labs}개 실습의 한국어 학습 기록. 문제 조건, 탐색 과정, 풀이와 배운 점. 붉은 사선이 가로지르는 방패 로고.</desc>',
    '<!-- Generated by scripts/build-readme-hero.py. Shield outline: Lucide (ISC); lettering: Pretendard (OFL). See site/assets/ for licenses. -->',
    '''<style>
      svg { --paper:#f8f9fb;--ink:#252b33;--muted:#68717c;--rule:#dce1e7;--red:#c33b43;color:var(--ink); }
      .paper { fill:var(--paper); }
      .ink { fill:var(--ink); }
      .muted { fill:var(--muted); }
      .rule { stroke:var(--rule); }
      .accent,.slash { fill:var(--red); }
      .shield { stroke:var(--ink); }
      @media(prefers-color-scheme:dark) {
        svg { --paper:#1c1f23;--ink:#edf0f3;--muted:#a1a9b3;--rule:#34393f;--red:#f0787f; }
      }
    </style>''',
    '<rect class="paper" width="1600" height="620" rx="8"/>',
    '<rect class="rule" x=".5" y=".5" width="1599" height="619" rx="7.5" fill="none"/>',
    '<rect class="accent" x="82" y="64" width="9" height="9"/>',
    label("WEB SECURITY / PERSONAL NOTES", 108, 76, 18, 550, "muted", tracking=1.8),
    label("PortSwigger", 76, 219, 100, 660, tracking=-2.3),
    label("Lab Notes", 79, 324, 100, 660, tracking=-2.3),
    label("문제 조건 · 탐색 과정 · 풀이와 배운 점", 84, 388, 27, 450, "muted"),
    '<path class="rule" d="M84 441H858M974 84V536" fill="none"/>',
    label(str(topics), 82, 517, 48, 600, tracking=-1),
    label("주제", 154, 514, 24, 450, "muted"),
    '<path class="rule" d="M252 483V520" fill="none"/>',
    label(str(labs), 292, 517, 48, 600, tracking=-1),
    label("실습", 399, 514, 24, 450, "muted"),
    '<g transform="translate(1085 111) scale(14.5)" fill="none">' + brand + '</g>',
    '<g style="--topic-icon-accent:var(--red)">',
    topic_icon("sql-injection", 1158, 500),
    topic_icon("authentication", 1246, 500),
    topic_icon("access-control-vulnerabilities", 1334, 500),
    '</g>',
    '</svg>',
]

destination = ROOT / "docs/assets/readme-hero.svg"
destination.parent.mkdir(parents=True, exist_ok=True)
destination.write_text("\n".join(parts) + "\n")
print(f"Wrote {destination.relative_to(ROOT)} ({destination.stat().st_size:,} bytes; {topics} topics, {labs} labs)")
