#!/usr/bin/env python3
"""Rebuild Faultline's outlined SVG artwork and fixed-light social PNG.

Dependencies: fonttools, brotli, cairosvg (and Cairo on the host).
"""

import html
import json
import math
import re
from pathlib import Path

import cairosvg
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
font = TTFont(ROOT / "site/assets/fonts/pretendard/PretendardVariable.woff2")
units = font["head"].unitsPerEm
cmap = font.getBestCmap()
glyph_sets = {}
BRAND = json.loads((ROOT / "site/brand.json").read_text())
SUBTITLE = BRAND["tagline"]


def number(value):
    return f"{value:.2f}".rstrip("0").rstrip(".") if value else "0"


def label(text, x, y, size, weight=450, color="ink", tracking=0):
    """Outline lettering so images need no embedded or external fonts."""
    if weight not in glyph_sets:
        glyph_sets[weight] = font.getGlyphSet(location={"wght": weight})
    glyphs = glyph_sets[weight]
    scale = size / units
    pen = SVGPathPen(glyphs, ntos=number)
    cursor = 0
    for char in text:
        glyph = glyphs[cmap[ord(char)]]
        glyph.draw(TransformPen(pen, (1, 0, 0, 1, cursor, 0)))
        cursor += glyph.width + tracking / scale
    return (
        f'<g class="{color}" data-label="{html.escape(text, quote=True)}" '
        f'transform="translate({number(x)} {number(y)}) scale({scale} {-scale})">'
        f'<path d="{pen.getCommands()}"/></g>'
    )


def shield():
    source = (ROOT / "site/assets/favicon/favicon.svg").read_text()
    body = re.search(r"<svg\b[^>]*>(.*?)</svg>", source, re.S).group(1)
    body = re.sub(r"<style\b[^>]*>.*?</style>|<title>.*?</title>|<!--.*?-->", "", body, flags=re.S).strip()
    # Clip the same 5.52-unit diagonal gap instead of using a luminance mask.
    # This preserves the approved logo in browsers and Cairo's alpha-only masks.
    normal_x, normal_y = math.sin(math.radians(43)), math.cos(math.radians(43))
    top_x = 12 + (-2.76 + 12 * normal_y) / normal_x
    left_y = 12 + (-2.76 + 12 * normal_x) / normal_y
    bottom_x = 24 - top_x
    right_y = 24 - left_y
    clip = (
        '<clipPath id="hero-split" clipPathUnits="userSpaceOnUse">'
        f'<path d="M0 0H{number(top_x)}L0 {number(left_y)}Z'
        f'M24 24H{number(bottom_x)}L24 {number(right_y)}Z"/>'
        '</clipPath>'
    )
    body = re.sub(r'<mask\b[^>]*>.*?</mask>', clip, body, flags=re.S)
    return body.replace('mask="url(#split)"', 'clip-path="url(#hero-split)"')


PALETTE = {"paper": "#f8f9fb", "ink": "#252b33", "muted": "#68717c", "rule": "#dce1e7", "red": "#c33b43"}
DARK = {"paper": "#1c1f23", "ink": "#edf0f3", "muted": "#a1a9b3", "rule": "#34393f", "red": "#f0787f"}


def styles(adaptive):
    def rules(colors):
        return (
            f'.paper{{fill:{colors["paper"]}}}'
            f'.ink{{fill:{colors["ink"]}}}'
            f'.muted{{fill:{colors["muted"]}}}'
            f'.rule{{stroke:{colors["rule"]}}}'
            f'.accent,.slash{{fill:{colors["red"]}}}'
            f'.shield{{stroke:{colors["ink"]}}}'
        )
    css = rules(PALETTE)
    if adaptive:
        css += "@media(prefers-color-scheme:dark){" + rules(DARK) + "}"
    return "<style>" + css + "</style>"


def artwork(social=False):
    width, height = (1200, 630) if social else (1600, 620)
    left = 64 if social else 84
    title_y, title_size = (288, 146) if social else (305, 196)
    subtitle_y, subtitle_size = (351, 26) if social else (378, 32)
    divider_x = 776 if social else 1004
    shield_x, shield_y, shield_scale = (842, 179, 11.6) if social else (1101, 139, 15)
    footer_y = 530 if social else 536
    top_y = 93 if social else 89
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}" role="img" aria-labelledby="hero-title hero-description">',
        f'<title id="hero-title">{html.escape(BRAND["name"])} — 웹 보안 기록</title>',
        f'<desc id="hero-description">{SUBTITLE} 붉은 사선이 가로지르는 방패 로고와 개념, 실습, 분석을 담는 웹 보안 저널.</desc>',
        '<!-- Generated by scripts/build-readme-hero.py. Shield outline: Lucide (ISC); lettering: Pretendard (OFL). See site/assets/ for licenses. -->',
        styles(adaptive=not social),
        f'<rect class="paper" width="{width}" height="{height}"/>',
        f'<rect class="rule" x=".5" y=".5" width="{width-1}" height="{height-1}" fill="none"/>',
        f'<path class="accent" d="M{left} {top_y-13}h24v3h-24z"/>',
        label("WEB SECURITY JOURNAL", left + 40, top_y, 17 if social else 19, 560, "muted", tracking=2),
        label(BRAND["name"], left - 8, title_y, title_size, 650, tracking=-3.5),
        label(SUBTITLE, left, subtitle_y, subtitle_size, 450, "muted"),
        # An offset seam repeats the direction of the shield's split quietly.
        f'<path class="rule" d="M{divider_x} 80V268l-32 30V{height-80}" fill="none"/>',
        f'<path class="rule" d="M{left} {footer_y-51}H{divider_x-100}" fill="none"/>',
        label("개념", left, footer_y, 24 if social else 27, 550),
        label("/", left + (79 if social else 93), footer_y, 24, 350, "muted"),
        label("실습", left + (121 if social else 143), footer_y, 24 if social else 27, 550),
        label("/", left + (200 if social else 236), footer_y, 24, 350, "muted"),
        label("분석", left + (242 if social else 286), footer_y, 24 if social else 27, 550),
        f'<g transform="translate({shield_x} {shield_y}) scale({shield_scale})" fill="none">{shield()}</g>',
        '</svg>',
    ]
    return "\n".join(parts) + "\n"


def write(relative, content):
    destination = ROOT / relative
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content)
    print(f"Wrote {relative} ({destination.stat().st_size:,} bytes)")
    return destination


write("docs/assets/readme-hero.svg", artwork())
social = artwork(social=True)
write("site/assets/og-image.svg", social)
preview = ROOT / "site/assets/og-image.png"
cairosvg.svg2png(bytestring=social.encode(), write_to=str(preview), output_width=1200, output_height=630)
print(f"Wrote {preview.relative_to(ROOT)} ({preview.stat().st_size:,} bytes; 1200 × 630)")
